# Generated by Django 5.1 on 2024-09-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0002_rename_paasword_adminlogin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='user',
            new_name='userid',
        ),
    ]
