# Generated by Django 5.1 on 2024-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(max_length=30),
        ),
    ]
