# Generated by Django 5.1 on 2024-09-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0005_session_alter_enquiry_enquirydate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='session',
        ),
    ]
