# Generated by Django 5.1 on 2024-09-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0007_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='tblSession',
        ),
    ]
