# Generated by Django 5.1 on 2024-09-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0008_rename_session_tblsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblsession',
            old_name='session',
            new_name='ses',
        ),
    ]
