# Generated by Django 5.1 on 2024-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0009_rename_session_tblsession_ses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.IntegerField(auto_created=(1, 1), primary_key=True, serialize=False),
        ),
    ]
