# Generated by Django 5.1 on 2024-09-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0010_alter_enquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
