# Generated by Django 5.1 on 2024-09-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0013_alter_enquiry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
