# Generated by Django 5.1 on 2024-09-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0014_tbl_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
