# Generated by Django 5.1 on 2024-09-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0017_studentlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
