# Generated by Django 5.1 on 2024-09-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0018_delete_studentlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
