# Generated by Django 5.1 on 2024-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0021_alter_student_aadharpic_alter_student_fees_sc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coursefees',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
