# Generated by Django 5.1 on 2024-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0022_student_coursefees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees_sc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
