# Generated by Django 5.0.6 on 2024-09-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0024_alter_student_aadharpic_alter_student_fees_sc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_course',
            name='course_duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
